# Code Generated by Sidekick is for learning and experimentation purposes only.
#!/bin/bash
IMAGE_TAG=$1

# Build Docker image on EC2 (alternatively, pull from registry)
docker build -t 4thtask:${IMAGE_TAG} .

# Stop existing canary container (if any)
docker stop canary-app || true
docker rm canary-app || true

# Start new canary container
docker run -d --name canary-app -p 8081:8080 4thtask:${IMAGE_TAG}

# (Optional) Add logic to keep both canary and stable running
# You might also want a load balancer to split traffic for proper canary deployment
