// Code Generated by Sidekick is for learning and experimentation purposes only.
pipeline {

    agent any

    environment {
        REMOTE_USER = "ec2-user"
        REMOTE_HOST = "13.62.86.188"   // Change to your EC2 Public IP/DNS
        APP_NAME = "4thtask"
        IMAGE_TAG = "canary-${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                timeout(time: 20, unit: 'MINUTES') {
                    sh "docker build -t $APP_NAME:$IMAGE_TAG ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "echo Deploy step here"
                // Example for real registry:
                // sh "docker tag ${APP_NAME}:${IMAGE_TAG} <your_registry>/<your_repo>:${IMAGE_TAG}"
                // sh "docker push <your_registry>/<your_repo>:${IMAGE_TAG}"
            }
        }

        stage('Deploy Canary Release') {
            steps {
                withCredentials([sshUserPrivateKey(
                    credentialsId: 'my-ec2-key',        // <-- Set this to the ID of your Jenkins credential
                    keyFileVariable: 'SSH_KEY'
                )]) {
                    // Copy deploy.sh and Dockerfile
                    sh """
                        scp -i $SSH_KEY -o StrictHostKeyChecking=no deploy.sh ${REMOTE_USER}@${REMOTE_HOST}:/home/${REMOTE_USER}/
                        scp -i $SSH_KEY -o StrictHostKeyChecking=no Dockerfile ${REMOTE_USER}@${REMOTE_HOST}:/home/${REMOTE_USER}/
                        ssh -i $SSH_KEY -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} 'chmod +x deploy.sh && ./deploy.sh ${IMAGE_TAG}'
                    """
                }
            }
        }
    }
}
